# AuthorizedOP 配置文件
# 为防止作弊者可以通过BUG从从控制台执行命令
# 这里提供指令开关
# true 为开启指令
# false 为关闭指令
是否开启指令管理: true
# 插件检测非法OP的速度
# 单位：tick(20tick = 1秒)
插件检测速度: 20
# 手动填写请注意格式
# 建议百度Yaml格式
# 格式写错会导致无法加载
# 建议第一次使用插件添加
获得OP授权的玩家: []